export enum AssignmentType {
  OPENING_PRAYER = 'openingPrayer',
  FINAL_PRAYER = 'finalPrayer',
  PRESIDENT = 'president',
  ASSIGNMENT_1 = 'assignment1',
  ASSIGNMENT_2 = 'assignment2',
  ASSIGNMENT_3 = 'assignment3',
  WHAT_HE_DID = 'whatHeDid',
  IMITATE = 'imitate',
  STARTING_A_CONVERSATION = 'startingAConversation',
  STARTING_A_CONVERSATION_ASSISTANT = 'startingAConversationAssistant',
  FOLLOWING_UP = 'followingUp',
  FOLLOWING_UP_ASSISTANT = 'followingUpAssistant',
  EXPLAINING_YOUR_BELIEFS = 'explainingYourBeliefs',
  EXPLAINING_YOUR_BELIEFS_ASSISTANT = 'explainingYourBeliefsAssistant',
  MAKING_DISCIPLES = 'makingDisciples',
  MAKING_DISCIPLES_ASSISTANT = 'makingDisciplesAssistant',
  CONGREGATION_BIBLE_STUDY = 'congregationBibleStudy',
  CONGREGATION_BIBLE_STUDY_READER = 'congregationBibleStudyReader',
  LOCAL_NEEDS = 'localNeeds',
  OTHER_PART_LIVING_AS_CHRISTIANS = 'otheAssignmentsLAC',
  SPEECH = 'speech',
  ASSISTANT_ADVISER = 'assistantAdviser'
}
